//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parts
    {
        public int IdPart { get; set; }
        public int IdCar { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Manufacturer { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public int Remain { get; set; }
        public double Price { get; set; }
        public int PartNum { get; set; }
        public string Original { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
