//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCar
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdCar { get; set; }
        public int Vin { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
    }
}
